[package]
name = "sparse-merkle-tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptoxide = "0.4.4"
hex = "0.4.3"
hexlit = "0.5.5"
