name: Tests

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.0.28-alpha

      - run: aiken fmt --check
      - run: aiken check -D
      - run: aiken build
      # - name: Run unit tests
      #   run: cargo test --verbose --workspace my_test
      #        cargo test --verbose --workspace test_contiguous
